language: go

go:
  - "1.16"
  - master
dist: trusty
services:
  - mariadb
  - docker
before_script:
  - make mariadb
  - go install github.com/mattn/goveralls
script:
  - make lint
  - go test -covermode=count -coverprofile=coverage.out ./...
after_success:
  - goveralls -service=travis-ci -coverprofile=coverage.out