language: go
go:
  - "1.17"
sudo: false
dist: trusty
notifications:
  email: false
services:
  - mariadb
  - docker
before_install:
  - go mod tidy
install:
  - github.com/mattn/goveralls
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
  sh -s -- -b $(go env GOPATH)/bin v1.42.1;
  - go get -v github.com/rubenv/sql-migrate/...
  - make mariadb
script:
  - golangci-lint run
  - go test -covermode=count -coverprofile=coverage.out ./...
after_success:
  - goveralls -service=travis-ci -coverprofile=coverage.out